image: reg-gitlab.btcbit.loc:3343/gitops/repos/docker-images/cicd-php82-node:1.0.0

stages:
  - code-check
  - test

include:
  - project: 'system/cd-templates'
    file:
      - code_review.yml
      - unit_test_sqlite.yml

variables:
  build: "build"
  MODULE: "btcbit-monolog"
  PROJECT: "btc"
  SKIP_PHPSTAN: "true"
  SKIP_RECTOR: "false"
  SKIP_CS_CHECK: "false"
